apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/<YOUR_ALB_CONTROLLER_ROLE_NAME>
