apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <YOUR-ECR-FRONTEND-IMAGE>
          ports:
            - containerPort: 80
      # Optional: add securityContext or other policies if needed
  