apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: LoadBalancer  # This triggers ALB via the ALB Ingress Controller
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
